version: '3.5'
services:
  alpine:
    container_name: oj-dev
    image: alpine:oj-dev
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    hostname: dev
    volumes:
      - ${TMP:-./tmp}/root:/root
      - ${DIR:-.}:/root/atcode
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.zsh_history:/root/.zsh_history
      - ${HOME}/.zshrc:/root/.zshrc
      - ${HOME}/.alias.d:/root/.alias.d
      - ${HOME}/.p10k.zsh:/root/.p10k.zsh
      - ${HOME}/.oh-my-zsh:/root/.oh-my-zsh
    networks:
      - dev
    command: tail -f /dev/null
    restart: always
    environment:
      TZ:
      TERM:
networks:
  dev:
    driver: bridge
    name: local
    external: true