version: '3.8'
services:
  minio:
    image: quay.io/minio/minio # 如果不支持x86-64-v2，使用quay.io/minio/minio:RELEASE.2024-11-01T01-57-10Z-cpuv1
    container_name: oj-minio
    hostname: "minio"
    ports:
      - "39000:9000" # api 端口
      - "39001:9001" # 控制台端口
    environment:
      MINIO_ROOT_USER: admin    #管理后台用户名
      MINIO_ROOT_PASSWORD: admin123456 #管理后台密码，最小8个字符
    volumes:
      - ${DIR:-.}/oss:/data               #映射当前目录下的data目录至容器内/data目录
      - ./config:/root/.minio/     #映射配置目录
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always
    networks:
      - oj_network
  npm:
    image: jlesage/nginx-proxy-manager:latest
    container_name: oj-npm
    ports:
      - "443:4443"
      - "80:8080"
      - "8181:8181"
    privileged: true
    restart: always
    volumes:
      - ${DIR:-.}/npm/data:/data
      - ${DIR:-.}/npm/letsencrypt:/etc/letsencrypt
      - ${DIR:-.}/resource:/resource
      - ${DIR:-.}/dist:/usr/share/nginx/html
    networks:
      - oj_network
networks:
  oj_network:
    driver: bridge