# 端口号
host: "oj"
gatWayHost: "http://gateway:4433/"
port: ":4212"
mode: "debug"
# 签名
sign: "ahutoj"
version: "1.0.0"
# 开始时间  雪花ID的配置
startTime: "2022-01-15"
machineID: 1
# 判题数据
dataPath: "./resource/Data/"
#封榜时间
terminal: 0.8  
# 图片存放路径
imagePath: "http://minio:9000/image"
#headPath:  "http://127.0.01:4379/image/head/"
#spjPath:   "http://127.0.01:4379/spj/"
# 是否开放注册
openRegisiters: true
# 外部判题相关配置
oss:
    host: "minio"
    port: 9000
    basepath: "./resource/"
    AccessKeyID: "Ej0Od1drI9V5F2PaT5DR"
    SecretAccessKey: "AzXkyd80IDakkKObiUNCQiPdvqVnhVmnCoH6XLka"#记得改
    UseSSL: false

forum:
    host: "127.0.0.1"
    port: 4498
    
mysql:  
    driver: "mysql"
    host: "mysql"
    port: 3306
    username: "root"
    dbname: "ahutoj"
    password: "123456"

redis:
    host: "redis"
    port: ":6379"
    db: 0
    pool_size: 100
    keepalive: 30
    password: "2019ahut"

log:
    level: "debug"
    filename: "ahutoj.log"
    max_size: 4194304

originLog:
    level: "debug"
    filename: "originjudge.log"
    max_size: 4194304
useOriginJudge: true
# 注册一个AtCoder判题机，首先配置ID前缀，配置公共密码 ID:prefix + 数字(最多支持 1-100) 
atCoderJudges:
    count: 20 
    prefix: "AOJjudge"
    password: "123456"
# 外部判题使用codeforce
codeForceJudge:   
    count: 20 
    prefix: "AOJjudge"
    password: "123456"
# 外部判题使用洛谷
luoguJudge:      
    count: 20 
    prefix: "AOJjudge"
    password: "123456"
gatWay:
    port: ":4433"
    maxqps: 100
    blackReq: 
useranalytics:
    port: ":4435"
    mysql:  
        driver: "mysql"
        host: "mysql"
        port: 3306
        username: "root"
        dbname: "ahutoj"
        password: "123456"
rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "ahutoj"
    password: "123456"