filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/logs/**/*.log'

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644